'use client';
import Link from 'next/link';
import { Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { DEVELOPERS, ISSUE_PRIORITIES, ISSUE_STATUSES, ISSUE_TYPES } from '@/types/issue';
import { useIssues } from '@/components/issues/issue-provider';
function IssuesContent() { const { issues, loading, error, removeIssue } = useIssues(); const searchParams = useSearchParams(); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [priority, setPriority] = useState(''); const [type, setType] = useState(''); const [assignee, setAssignee] = useState(''); const [projectId, setProjectId] = useState(''); const [deletingId, setDeletingId] = useState<number | null>(null); useEffect(() => setProjectId(searchParams.get('project') ?? ''), [searchParams]); const filtered = issues.filter((issue) => issue.title.toLowerCase().includes(search.toLowerCase()) && (!status || issue.status === status) && (!priority || issue.priority === priority) && (!type || issue.type === type) && (!assignee || issue.assignee === assignee) && (!projectId || issue.projectId === Number(projectId))); async function remove(id: number) { if (!window.confirm('Excluir esta issue permanentemente?')) return; setDeletingId(id); try { await removeIssue(id); } catch { window.alert('Não foi possível excluir a issue.'); } finally { setDeletingId(null); } }
  if (loading) return <p>Carregando...</p>; return <><div className="page-head"><div><h1>Issues</h1><p className="muted">Filtre, acompanhe e atualize o trabalho.</p></div><Link className="button" href="/issues/nova">Nova Issue</Link></div>{error && <p className="error">{error}</p>}<div className="card filters"><label className="full">Busca por título<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Pesquisar issue" /></label>{[['Status', status, setStatus, ISSUE_STATUSES], ['Prioridade', priority, setPriority, ISSUE_PRIORITIES], ['Tipo', type, setType, ISSUE_TYPES], ['Responsável', assignee, setAssignee, DEVELOPERS]].map(([label, value, setter, options]) => <label key={label as string}>{label as string}<select value={value as string} onChange={(event) => (setter as (value: string) => void)(event.target.value)}><option value="">Todos</option>{(options as readonly string[]).map((option) => <option key={option}>{option}</option>)}</select></label>)}</div><div className="card table-wrap" style={{ marginTop: 16 }}>{filtered.length === 0 ? <div className="empty">Nenhuma issue encontrada. <Link href="/issues/nova">Criar uma issue</Link></div> : <table><thead><tr><th>ID</th><th>Título</th><th>Tipo</th><th>Prioridade</th><th>Status</th><th>Responsável</th><th>Ações</th></tr></thead><tbody>{filtered.map((issue) => <tr key={issue.id}><td>#{issue.id}</td><td><Link href={`/issues/${issue.id}`}>{issue.title}</Link></td><td>{issue.type}</td><td><span className={`badge ${issue.priority === 'CRITICA' ? 'critical' : ''}`}>{issue.priority}</span></td><td><span className="badge">{issue.status}</span></td><td>{issue.assignee}</td><td className="actions"><Link className="button secondary" href={`/issues/${issue.id}`}>Abrir</Link><button className="button danger" onClick={() => void remove(issue.id)} disabled={deletingId === issue.id}>{deletingId === issue.id ? 'Excluindo...' : 'Excluir'}</button></td></tr>)}</tbody></table>}</div></>; }
export default function IssuesPage() { return <Suspense fallback={<p>Carregando...</p>}><IssuesContent /></Suspense>; }
